env:
  es2021: true
  node: true
  jest: true

  plugins:
  - jest

extends:
  - airbnb-base
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 12
  sourceType: module
  
parserOptions:
  ecmaVersion: 2021
rules:
  no-console: 0
  import/extensions: 0
  import/no-named-as-default: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]